name: Release

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.4"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Try building
      run: python main.py
    - name: Upload release
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo "Uploading release"
        VERSION="$(python release_name.py)"
        mv big_file_merged-patched.apk "piko-v$VERSION.apk"
        gh release create --latest "$VERSION" piko*.apk
